/*
 * RCC.h
 *
 *  Created on: Sep 5, 2024
 *      Author: erhan
 */

#ifndef INC_RCC_H_
#define INC_RCC_H_

#include <stm32f303xx.h>

/*
 * RCC AHB Peripherals Clock Control Macro Definitions
 */

#define RCC_AHB_CLK_EN(x)		do{ uint32_t tempValue = 0;									\
									SET_BIT(RCC->AHBENR, x);				\
									tempValue = READ_BIT(RCC->AHBENR, x);	\
									UNUSED(tempValue);										\
								}while(0)

#define RCC_AHB_CLK_DIS(x)		CLEAR_BIT(RCC->AHBENR, x)

/*
 * RCC APB1 Peripherals Clock Control Macro Definitions
 */

#define RCC_APB1_CLK_EN(x)		do{ uint32_t tempValue = 0;									\
									SET_BIT(RCC->APB1ENR, x);				\
									tempValue = READ_BIT(RCC->APB1ENR, x);	\
									UNUSED(tempValue);										\
								}while(0)

#define RCC_APB1_CLK_DIS(x)		CLEAR_BIT(RCC->APB1ENR, x)

/*
 * RCC APB2 Peripherals Clock Control Macro Definitions
 */

#define RCC_APB2_CLK_EN(x)		do{ uint32_t tempValue = 0;									\
									SET_BIT(RCC->APB2ENR, x);				\
									tempValue = READ_BIT(RCC->APB2ENR, x);	\
									UNUSED(tempValue);										\
								}while(0)

#define RCC_APB2_CLK_DIS(x)		CLEAR_BIT(RCC->APB2ENR, x)



#define RCC_GPIOA_CLK_EN()		RCC_AHB_CLK_EN(RCC_AHBENR_GPIOAEN)
#define RCC_GPIOA_CLK_DIS()		RCC_AHB_CLK_DIS(RCC_AHBENR_GPIOAEN)

#define RCC_GPIOB_CLK_EN()		RCC_AHB_CLK_EN(RCC_AHBENR_GPIOBEN)
#define RCC_GPIOB_CLK_DIS()		RCC_AHB_CLK_DIS(RCC_AHBENR_GPIOBEN)

#define RCC_GPIOC_CLK_EN()		RCC_AHB_CLK_EN(RCC_AHBENR_GPIOCEN)
#define RCC_GPIOC_CLK_DIS()		RCC_AHB_CLK_DIS(RCC_AHBENR_GPIOCEN)

#define RCC_GPIOD_CLK_EN()		RCC_AHB_CLK_EN(RCC_AHBENR_GPIODEN)
#define RCC_GPIOD_CLK_DIS()		RCC_AHB_CLK_DIS(RCC_AHBENR_GPIODEN)

#define RCC_GPIOF_CLK_EN()		RCC_AHB_CLK_EN(RCC_AHBENR_GPIOFEN)
#define RCC_GPIOF_CLK_DIS()		RCC_AHB_CLK_DIS(RCC_AHBENR_GPIOFEN)

#define RCC_GPIOG_CLK_EN()		RCC_AHB_CLK_EN(RCC_AHBENR_GPIOGEN)
#define RCC_GPIOG_CLK_DIS()		RCC_AHB_CLK_DIS(RCC_AHBENR_GPIOGEN)

#define RCC_GPIOH_CLK_EN()		RCC_AHB_CLK_EN(RCC_AHBENR_GPIOHEN)
#define RCC_GPIOH_CLK_DIS()		RCC_AHB_CLK_DIS(RCC_AHBENR_GPIOHEN)

#define RCC_GPIOH_CLK_EN()		RCC_AHB_CLK_EN(RCC_AHBENR_GPIOHEN)
#define RCC_GPIOH_CLK_DIS()		RCC_AHB_CLK_DIS(RCC_AHBENR_GPIOHEN)

#define RCC_SYSCFG_CLK_EN()		RCC_APB2_CLK_EN(RCC_ABP2ENR_SYSCFG)
#define RCC_SYSCFG_CLK_DIS()	RCC_APB2_CLK_DIS(RCC_APB2ENR_SYSCFG)

#define RCC_SPI1_CLK_EN()		RCC_APB2_CLK_EN(RCC_APB2ENR_SPI1EN)
#define RCC_SPI1_CLK_DIS()		RCC_APB2_CLK_DIS(RCC_APB2ENR_SPI1EN)

#define RCC_SPI4_CLK_EN()		RCC_APB2_CLK_EN(RCC_APB2ENR_SPI4EN)
#define RCC_SPI4_CLK_DIS()		RCC_APB2_CLK_DIS(RCC_APB2ENR_SPI4EN)

#define RCC_SPI2_CLK_EN()		RCC_APB1_CLK_EN(RCC_APB1ENR_SPI2EN)
#define RCC_SPI2_CLK_DIS()		RCC_APB1_CLK_DIS(RCC_APB1ENR_SPI2EN)

#define RCC_SPI3_CLK_EN()		RCC_APB1_CLK_EN(RCC_APB1ENR_SPI3EN)
#define RCC_SPI3_CLK_DIS()		RCC_APB1_CLK_DIS(RCC_APB1ENR_SPI3EN)

#define RCC_USART1_CLK_EN()		RCC_APB2_CLK_EN(RCC_APB2ENR_USART1EN)
#define RCC_USART1_CLK_DIS()	RCC_APB2_CLK_DIS(RCC_APB2ENR_USART1EN)

#define RCC_USART2_CLK_EN()		RCC_APB1_CLK_EN(RCC_APB1ENR_USART2EN)
#define RCC_USART2_CLK_DIS()	RCC_APB1_CLK_DIS(RCC_APB1ENR_USART2EN)

#define RCC_USART3_CLK_EN()		RCC_APB1_CLK_EN(RCC_APB1ENR_USART3EN)
#define RCC_USART3_CLK_DIS()	RCC_APB1_CLK_DIS(RCC_APB1ENR_USART3EN)

#define RCC_UART4_CLK_EN()		RCC_APB1_CLK_EN(RCC_APB1ENR_UART4EN)
#define RCC_UART4_CLK_DIS()		RCC_APB1_CLK_DIS(RCC_APB1ENR_UART4EN)

#define RCC_UART5_CLK_EN()		RCC_APB1_CLK_EN(RCC_APB1ENR_UART5EN)
#define RCC_UART5_CLK_DIS()		RCC_APB1_CLK_DIS(RCC_APB1ENR_UART5EN)

#define RCC_I2C1_CLK_EN()		RCC_APB1_CLK_EN(RCC_APB1ENR_I2C1EN)
#define RCC_I2C1_CLK_DIS()		RCC_APB1_CLK_DIS(RCC_APB1ENR_I2C1EN)

#define RCC_I2C2_CLK_EN()		RCC_APB1_CLK_EN(RCC_APB1ENR_I2C2EN)
#define RCC_I2C2_CLK_DIS()		RCC_APB1_CLK_DIS(RCC_APB1ENR_I2C2EN)

#define RCC_I2C3_CLK_EN()		RCC_APB1_CLK_EN(RCC_APB1ENR_I2C3EN)
#define RCC_I2C3_CLK_DIS()		RCC_APB1_CLK_DIS(RCC_APB1ENR_I2C3EN)

uint32_t RCC_GetSystemClock(void);
uint32_t RCC_GetHClock(void);
uint32_t RCC_GetP1Clock(void);
uint32_t RCC_GetP2Clock(void);

#endif /* INC_RCC_H_ */
